#!/bin/bash
# create-pr.sh
# Creates a pull request in Azure Repos and links it to the work item
#
# Usage: ./create-pr.sh <work-item-id> <branch-name> <workflow-type> <access-token>

set -e

WORK_ITEM_ID="$1"
BRANCH_NAME="$2"
WORKFLOW_TYPE="$3"
ACCESS_TOKEN="$4"

# Defaults from environment or fallback
ORG="${AZURE_DEVOPS_ORG:-jasonpaffES}"
PROJECT="${AZURE_DEVOPS_PROJECT:-Head Shakers}"
TARGET_REPO="${TARGET_REPO:-head-shakers}"
TARGET_BRANCH="${TARGET_BRANCH:-main}"

# URL encode the project name
PROJECT_ENCODED=$(echo "$PROJECT" | sed 's/ /%20/g')

if [ -z "$WORK_ITEM_ID" ] || [ -z "$BRANCH_NAME" ] || [ -z "$WORKFLOW_TYPE" ] || [ -z "$ACCESS_TOKEN" ]; then
  echo "Usage: $0 <work-item-id> <branch-name> <workflow-type> <access-token>"
  exit 1
fi

echo "Creating pull request..."
echo "Branch: $BRANCH_NAME -> $TARGET_BRANCH"
echo "Repository: $TARGET_REPO"

# Get repository ID
REPOS_URL="https://dev.azure.com/$ORG/$PROJECT_ENCODED/_apis/git/repositories/$TARGET_REPO?api-version=7.0"
REPO_RESPONSE=$(curl -s -H "Authorization: Bearer $ACCESS_TOKEN" "$REPOS_URL")
REPO_ID=$(echo "$REPO_RESPONSE" | jq -r '.id')

if [ -z "$REPO_ID" ] || [ "$REPO_ID" == "null" ]; then
  echo "Error: Could not find repository: $TARGET_REPO"
  echo "$REPO_RESPONSE"
  exit 1
fi

echo "Repository ID: $REPO_ID"

# Determine PR title based on workflow type
case "$WORKFLOW_TYPE" in
  "quick-fix")
    PR_TITLE="🔧 Quick Fix: Work Item #$WORK_ITEM_ID"
    PR_DESCRIPTION="Automated quick fix generated by AI pipeline.\n\n**Work Item:** #$WORK_ITEM_ID\n**Type:** Quick Fix (trivial change)\n\n---\n\n⚠️ **Review Checklist:**\n- [ ] Changes are minimal and targeted\n- [ ] No unintended side effects\n- [ ] Tests pass (if applicable)"
    ;;
  "implement")
    PR_TITLE="✨ Implementation: Work Item #$WORK_ITEM_ID"
    PR_DESCRIPTION="Implementation generated from approved plan by AI pipeline.\n\n**Work Item:** #$WORK_ITEM_ID\n**Type:** Planned Implementation\n\n---\n\n⚠️ **Review Checklist:**\n- [ ] Implementation matches the approved plan\n- [ ] Code follows project conventions\n- [ ] Tests included/updated\n- [ ] No unintended changes"
    ;;
  *)
    PR_TITLE="🤖 AI Generated: Work Item #$WORK_ITEM_ID"
    PR_DESCRIPTION="Changes generated by AI pipeline.\n\n**Work Item:** #$WORK_ITEM_ID"
    ;;
esac

# Create the pull request
PR_URL="https://dev.azure.com/$ORG/$PROJECT_ENCODED/_apis/git/repositories/$REPO_ID/pullrequests?api-version=7.0"

PR_PAYLOAD=$(cat <<EOF
{
  "sourceRefName": "refs/heads/$BRANCH_NAME",
  "targetRefName": "refs/heads/$TARGET_BRANCH",
  "title": "$PR_TITLE",
  "description": "$PR_DESCRIPTION",
  "workItemRefs": [
    {
      "id": "$WORK_ITEM_ID"
    }
  ],
  "isDraft": false
}
EOF
)

PR_RESPONSE=$(curl -s -X POST \
  -H "Authorization: Bearer $ACCESS_TOKEN" \
  -H "Content-Type: application/json" \
  -d "$PR_PAYLOAD" \
  "$PR_URL")

PR_ID=$(echo "$PR_RESPONSE" | jq -r '.pullRequestId')
PR_WEB_URL=$(echo "$PR_RESPONSE" | jq -r '.url' | sed 's/_apis\/git\/repositories.*/_git\/'"$TARGET_REPO"'\/pullrequest\/'"$PR_ID"'/')

if [ -z "$PR_ID" ] || [ "$PR_ID" == "null" ]; then
  echo "Error: Failed to create pull request"
  echo "$PR_RESPONSE"
  exit 1
fi

echo "----------------------------------------"
echo "Pull Request created successfully!"
echo "PR ID: $PR_ID"
echo "URL: https://dev.azure.com/$ORG/$PROJECT_ENCODED/_git/$TARGET_REPO/pullrequest/$PR_ID"
echo "----------------------------------------"

# Add a comment to the work item about the PR
COMMENT_URL="https://dev.azure.com/$ORG/$PROJECT_ENCODED/_apis/wit/workitems/$WORK_ITEM_ID/comments?api-version=7.0-preview.3"

COMMENT_PAYLOAD=$(cat <<EOF
{
  "text": "🚀 **Pull Request Created**\n\nAI pipeline has created a pull request for this work item.\n\n**PR:** [#$PR_ID](https://dev.azure.com/$ORG/$PROJECT_ENCODED/_git/$TARGET_REPO/pullrequest/$PR_ID)\n**Branch:** \`$BRANCH_NAME\`\n**Type:** $WORKFLOW_TYPE\n\n**Next Steps:**\n1. Review the pull request\n2. Approve and merge when ready"
}
EOF
)

curl -s -X POST \
  -H "Authorization: Bearer $ACCESS_TOKEN" \
  -H "Content-Type: application/json" \
  -d "$COMMENT_PAYLOAD" \
  "$COMMENT_URL" > /dev/null

echo "Comment added to work item"

# Output PR ID for pipeline use
echo "##vso[task.setvariable variable=PR_ID]$PR_ID"
